#!/usr/bin/env python3

__author__ = "Scott Teresi"

"""
This code serves to import the observation key/plotID data and return a
dictionary and a dataframe
"""

import pandas as pd


def obs_data(file_name):
    """ Import the obs_2019_key.csv

    Args:
        path_to_file (str)

    """

    obs_data = pd.read_csv(
        file_name,
        sep=',',
        header='infer')

    return obs_data


def geno_plot_dict(df):
    """ Extract a dictionary of plotID vs. genotype from a pandas.DataFrame.

    Args:
        pandas.DataFrame (i.e. obs_data generated by previous function)

    """
    # Converts dataframe columns into lists.
    geno = df['Genotype'].tolist()
    plot = df['Plot'].tolist()
    # Creates the dictionary with plotID as key and genotype as value.
    geno_plot_dict = dict(zip(plot, geno))

    return geno_plot_dict
